import swaggerAutogen from "swagger-autogen";
import env from "../config/env";

const doc = {
    info: {
        version: "1.0.0",
        title: "API Documentation",
        description: "Docs automatically generated by <b>Sirojiddin's auto docs</b> module."
    },
    host: `10.100.26.3:${env.PORT}`,
    schemes: ["http"],
    components: {
        securitySchemes: {
            bearerAuth: {
                type: "http",
                scheme: "bearer"
            }
        }
    },
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header",
            name: "Authorization"
        }
    },
};

const outputFile = "../../src/docs/swagger-output.json";
const endpointsFiles = ["../../src/app.ts"]; // Updated for TypeScript

swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
    import("../../src/app.ts"); // Ensure TypeScript handles the import
});
